### PR TITLE
update hash mkmf

### PR DESCRIPTION
**Pull request by raphaeldussin**
this will update to the hash used currently in MOM6-examples.
We might want to consider owning our own fork of mkmf

### CODE REVIEW

**Comment by kshedstrom** [comment]
We have a fork of mkmf which differs slightly from that of GFDL. I think you added a file for a machine named triton - do we still want that?

**Comment by raphaeldussin** [comment]
Oops completely forgot about that. If @MJHarrison-GFDL, @adcroft and @Hallberg-NOAA are ok with it, I’d be happy to replace the mkmf submodule by our fork so we can add our custom templates. It doesn’t look like mkmf has a lot of activity so keeping the fork up to date should not be too much work.

**Comment by raphaeldussin** [comment]
In the meantime, we can merge this PR so the repo works and then move on to the next step.

**Comment by kshedstrom** [comment]
Can you update the PR to point to our fork?

**Comment by MJHarrison-GFDL** [comment]
closing

**Pull request closed without merging**
